const routeToAppMap = {
    "/date_range/{date_range_id}": "analytics and risk",
    "/es/ps": "analytic",
    "/es/pc": "analytic",
    "/hs/summary": "analytic",
    "/pdd/ps": "analytic",
    "/pdd/sd": "analytic",
    "/pdd/es": "analytic",
    "/pdd/dd": "analytic",
    "/pi/prr": "analytic",
    "/pi/sd": "analytic",
    "/create_portfolio": "create portfolio",
    "/update_portfolio": "create portfolio",
    "/upload_portfolio": "create portfolio",
    "/delete_custom_portfolio": "create portfolio",
    "/fs_status": "analytic",
    "/rmd/fs": "risk model",
    "/rmd/ss": "risk model",
    "/pa/select_portfolio": "strategy builder",
    "/pa/upload_portfolio": "strategy builder",
    "/pa/manual_update": "strategy builder",
    "/pa/analytics": "strategy builder",
    "/optimizer-dropdown-data": "strategy builder",
    "/create-optimizer": "strategy builder",
    "/create-backtest": "strategy builder",
    "/strategy/status": "strategy builder",
    "/alpha_library/standard": "strategy builder",
    "/alpha_library/user_created": "strategy builder",
    "/alpha_library/upload_alpha": "strategy builder",
    "/alpha_library/delete_alpha": "strategy builder",
    "/strategy/delete_strategy_portfolio": "strategy builder",
    "/la/ps": "analytic",
    "/la/pc": "analytic",
    "/initiate-analytics": "strategy builder"
  };

export { routeToAppMap };